# Generated by Django 4.2.24 on 2025-09-23 04:59

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('args', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('kwargs', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority', models.IntegerField(db_index=True, default=100, help_text='Lower numbers run earlier')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=24)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('aps_job_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('result', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'next_run_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'next_run_at', 'priority'], name='core_queued_status_efe943_idx')],
            },
        ),
    ]
