# Generated by Django 4.2.24 on 2025-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_integrationsecret_service_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttemplate',
            name='default_env',
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='db_type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongodb', 'MongoDB')], default='postgres', max_length=20),
        ),
    ]
