# Generated by Django 4.2.24 on 2025-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_queuedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentstep',
            name='step_key',
            field=models.CharField(choices=[('project-create', 'Project Creation'), ('backend-create', 'Backend Creation'), ('backend-git-attach', 'Backend Git Attachment'), ('backend-build-config', 'Backend Build Configuration'), ('frontend-create', 'Frontend Creation'), ('frontend-git-attach', 'Frontend Git Attachment'), ('frontend-build-config', 'Frontend Build Configuration'), ('backend-service-env-set', 'Backend Environment Setup'), ('db-create', 'Database Creation'), ('db-deploy', 'Database Deployment'), ('backend-deploy', 'Backend Deployment'), ('frontend-deploy', 'Frontend Deployment'), ('backend-wait-deploy', 'Wait for Backend Deployment Completion'), ('frontend-wait-deploy', 'Wait for Frontend Deployment Completion'), ('backend-domains-create', 'Backend Domain Creation'), ('frontend-domains-create', 'Frontend Domain Creation'), ('domains-wait-propagation', 'Wait for Domains Propagation'), ('health-check', 'Health Check'), ('health-retry', 'Health Retry'), ('create-superuser', 'Create Superuser'), ('email-notify-success', 'Send Email Notification')], max_length=50),
        ),
    ]
