# Generated by Django 4.2.24 on 2025-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_projecttemplate_default_env_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='env_vars',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='service_type',
            field=models.CharField(choices=[('backend', 'Backend Service'), ('frontend', 'Frontend Service'), ('db', 'Database'), ('worker', 'Worker'), ('cron', 'Cron Job')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantservice',
            name='service_type',
            field=models.CharField(choices=[('backend', 'Backend Service'), ('frontend', 'Frontend Service'), ('db', 'Database'), ('worker', 'Worker'), ('cron', 'Cron Job')], max_length=20),
        ),
    ]
