# Generated by Django 4.2.24 on 2025-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicetemplate_env_vars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetemplate',
            name='internal_provision_token_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
