# Generated by Django 4.2.24 on 2025-09-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servicetemplate_internal_provision_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment', to='core.tenant'),
        ),
    ]
